Sources seed
RHEnVision/provisioning-compose pull request #4
Opened 2023-07-20 12:56 UTC by lzap

Two commits.

Seeding is now not a separate container, it did not work for "backend" (tried to migrate with backend-dev container). Since migration is extremely fast (takes about a second), running it before running the service should not be a problem.

This takes seed script from our main repo here, I verified it works.

```
[lzap@zzzap provisioning-compose]$ ./sources_seed/seed.sh 
{"sources":[{"availability_status":"in_progress","id":"1","created_at":"2023-07-20T12:33:47Z","updated_at":"2023-07-20T12:33:47Z","name":"Amazon source","uid":"2256035d-f6b4-423a-82ba-2461c0d4d43b","app_creation_workflow":"manual_configuration","source_type_id":"1"}],"applications":[{"id":"1","created_at":"2023-07-20T12:33:47Z","updated_at":"2023-07-20T12:33:47Z","availability_status":"in_progress","source_id":"1","application_type_id":"1"}],"endpoints":[],"authentications":[{"id":"1","authtype":"provisioning-arn","username":"arn:aws:iam::399777895069:role/satellite-services-role","availability_status":"in_progress","resource_type":"Application","resource_id":"1"}]}
{"sources":[{"availability_status":"in_progress","id":"2","created_at":"2023-07-20T12:33:47Z","updated_at":"2023-07-20T12:33:47Z","name":"Azure source","uid":"d7cc28a7-1f6b-443b-99d9-61c507b02058","app_creation_workflow":"manual_configuration","source_type_id":"8"}],"applications":[{"id":"2","created_at":"2023-07-20T12:33:47Z","updated_at":"2023-07-20T12:33:47Z","availability_status":"in_progress","source_id":"2","application_type_id":"1"}],"endpoints":[],"authentications":[{"id":"2","authtype":"provisioning_lighthouse_subscription_id","username":"2fd0879a-3149-4750-a10f-803f73586ad3","availability_status":"in_progress","resource_type":"Application","resource_id":"2"}]}
{"sources":[{"availability_status":"in_progress","id":"3","created_at":"2023-07-20T12:33:47Z","updated_at":"2023-07-20T12:33:47Z","name":"Google source","uid":"f1a04b15-99b6-4c3c-8b60-5d18dfb92d2c","app_creation_workflow":"manual_configuration","source_type_id":"12"}],"applications":[{"id":"3","created_at":"2023-07-20T12:33:47Z","updated_at":"2023-07-20T12:33:47Z","availability_status":"in_progress","source_id":"3","application_type_id":"1"}],"endpoints":[],"authentications":[{"id":"3","authtype":"provisioning_project_id","username":"redhat-360508","availability_status":"in_progress","resource_type":"Application","resource_id":"3"}]}
[lzap@zzzap provisioning-compose]$ curl-local GET /provisioning/v1/sources
[{"id":"1","name":"Amazon source","source_type_id":"1","uid":"2256035d-f6b4-423a-82ba-2461c0d4d43b"},{"id":"2","name":"Azure source","source_type_id":"8","uid":"d7cc28a7-1f6b-443b-99d9-61c507b02058"},{"id":"3","name":"Google source","source_type_id":"12","uid":"f1a04b15-99b6-4c3c-8b60-5d18dfb92d2c"}]
```

2023-07-23 19:45 UTC, amirfefer reviewed
Thanks @lzap, this change works under docker as well 👍 
I left a few comments

2023-07-23 19:45 UTC, amirfefer commented on compose.yml
> +      - ${EXPOSED_FRONTEND_DEV_PORT:-8008}:${FRONTEND_DEV_PORT:-8000}
wouldn't it be better to keep the default chrome frontend as 1337?
also, 8000 is already the default for the backend

2023-07-23 19:45 UTC, amirfefer commented on sources_seed/identity_header.sh
> +  IDENTITY=$(echo "{\"identity\": {\"type\": \"User\", \"account_number\":\"$1\", \"internal\":{\"org_id\":\"$2\"}}}" | base64 $B64OPTS)
The notifications service  needs  the identity header to include a user object to function properly, as following
```json
"identity":{"type":"User","account_number":"","org_id":"","user":{"username":"","email":"","first_name":"","last_name":""}}
```
would we like to add it to this generator to make it easier to consume?

2023-07-23 19:45 UTC, amirfefer commented on compose.yml
> +      - "/pbackend migrate && /pbackend api"
this overrides the default entrypoint from the Dockerfile which enables live reload, 

```yml
entrypoint: 
      - bash
      -  "-c"
      - /pbackend migrate && $HOME/go/bin/CompileDaemon -build="go build -buildvcs=false -o /build/pbackend ./cmd/pbackend" -command="/build/pbackend api"
```

or instead, we can add an env variable for enabling live reload

2023-07-24 07:28 UTC, lzap commented on compose.yml
> +      - ${EXPOSED_FRONTEND_DEV_PORT:-8008}:${FRONTEND_DEV_PORT:-8000}
Absolutely this was a copy-paste error.

2023-07-24 07:34 UTC, lzap commented on sources_seed/identity_header.sh
> +  IDENTITY=$(echo "{\"identity\": {\"type\": \"User\", \"account_number\":\"$1\", \"internal\":{\"org_id\":\"$2\"}}}" | base64 $B64OPTS)
Sure.

2023-07-24 07:37 UTC, lzap commented on compose.yml
> +      - "/pbackend migrate && /pbackend api"
This line is for backend not backend-dev, but you are right. This was not intentional.

2023-07-24 07:37 UTC, lzap commented
Rebased.

2023-07-24 11:59 UTC, amirfefer requested changes
Thanks @lzap,
The backend-dev migrates well but fails to run the api server

2023-07-24 11:59 UTC, amirfefer commented on compose.yml
> +      - "go run ./cmd/pbackend migrate && $HOME/go/bin/CompileDaemon -build='go build -buildvcs=false -o /build/pbackend ./cmd/pbackend' -command='/build/pbackend api'"
the var `$HOME` results with the host's home, not the container's home, and it fails to launch.
we can change the `ENTRYPOINT` in the dockerfike instead, or using the hardcoded home of the container `/opt/app-root/src/`

2023-07-24 12:14 UTC, lzap commented
Sure how about this (untested)? If it does not work I can hardcode the path.

2023-07-24 12:44 UTC, amirfefer approved these changes
Great, works well 👍

2023-07-24 12:45 UTC, merged